### ISSUE TITLE
The remote server returned an error: (407) Proxy Authentication Required.

### ISSUE THREAD

**Issue by glusher** [KoenZomers/KeePassOneDriveSync#10]
Getting this error from behind a corporate proxy.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

KeePass
    Assembly Version: 2.30.0.15916
    Win32 Version: 2.30.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

KoenZomersKeePassOneDriveSync
    Assembly Version: 1.3.3.1
    Win32 Version: 1.3.3.1
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/feXsTTBK3YjWnapjFROG/KoenZomersKeePassOneDriveSync.dll

Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/feXsTTBK3YjWnapjFROG/Newtonsoft.Json.DLL

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

KeePassRPC
    Assembly Version: 2.0.15.18184
    Win32 Version: 1.5.4.0
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/1BUmVnZrQEad9Zn1Wwon/KeePassRPC.dll

Fleck2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/1BUmVnZrQEad9Zn1Wwon/Fleck2.DLL

DomainPublicSuffix
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/1BUmVnZrQEad9Zn1Wwon/DomainPublicSuffix.DLL

Jayrock
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.11214.1056
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/1BUmVnZrQEad9Zn1Wwon/Jayrock.DLL

KeePassRPC.Mono.Security
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/1BUmVnZrQEad9Zn1Wwon/KeePassRPC.Mono.Security.DLL

KeePass.XmlSerializers
    Assembly Version: 2.30.0.15916
    Win32 Version: 2.30.0.15916
##     CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL

System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll

Jayrock.Json
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.13422.2206
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/1BUmVnZrQEad9Zn1Wwon/Jayrock.Json.DLL

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

KoenZomers.OneDrive.Api
    Assembly Version: 1.3.1.0
    Win32 Version: 1.3.1.0
##     CodeBase: file:///C:/Users/09155112/AppData/Local/KeePass/PluginCache/feXsTTBK3YjWnapjFROG/KoenZomers.OneDrive.Api.DLL

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
##     CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll

System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.114.0 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll

System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KoenZomers** [comment]
What kind of authentication does your proxy require? Did you try the different options in KeePass under Tools -> Options -> Advanced -> Proxy? The plugin takes over these settings from KeePass.

**Comment by willougd** [comment]
I have the same issue and mine use ActiveDirectory authentication.  When I run an update inside keepass it doesn't fail.  But the plugin does.

**Comment by KoenZomers** [comment]
That's interesting. I unfortunately don't have an authenticated proxy to test this against, so am unable at this point to investigate and resolve it.

**Comment by KoenZomers** [comment]
Give this a try again with the version I've just released, v1.4.4.0. I've fixed quite a few proxy issues in it. Hopefully this fixes it for you as well. Still ensure you have your proxy configured in KeePass settings as described at the bottom of https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Configuration.md

**Comment by willougd** [comment]
Same error as before.  Proxy authentication required.  One thing to note.  It does login / authenticate / ask for permissions.  Its seems once its done with the authentication part is when it fails.

**Comment by KoenZomers** [comment]
I've had positive feedback from others using proxies that it now works for them. How did you configure the proxy settings in KeePass?

**Comment by willougd** [comment]
using system default.  Our proxy use domain authentication.

**Comment by KoenZomers** [comment]
It may be that you need to configure the proxy url as the intranet zone in Internet Explorer before it is allowed to relay your domain credentials to the proxy. Can you try explicitly providing your domain credentials in the KeePass proxy configuration to see if it does work then?

**Comment by willougd** [comment]
Hard coding the proxy settings makes the program freeze after I authenticate.  My keepass isn't that big so I'm not sure why its freezing?

**Comment by KoenZomers** [comment]
Are you familiar with Fiddler and can you examine the network trace from it to see what goes wrong?

**Comment by willougd** [comment]
I keep getting the below..  

I do have fiddler up Just not sure what can help you?

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at KoenZomers.OneDrive.Api.OneDriveApi.<DownloadItemAndSaveAs>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomersKeePassOneDriveSync.KeePassDatabase.<SyncDatabase>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KoenZomersKeePassOneDriveSync.KoenZomersKeePassOneDriveSyncExt.<OnKeePassDatabaseOpened>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.32.0.23563
    Win32 Version: 2.32.0.0
    CodeBase: file:///C:/Users/willougd/Downloads/KeePass-2.32/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34285 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34283 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
KoenZomersKeePassOneDriveSync
    Assembly Version: 1.4.4.0
    Win32 Version: 1.4.4.0
    CodeBase: file:///C:/Users/willougd/AppData/Local/KeePass/PluginCache/DsCdPVEnlofsAPgS8vr9/KoenZomersKeePassOneDriveSync.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/willougd/AppData/Local/KeePass/PluginCache/DsCdPVEnlofsAPgS8vr9/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
CredentialManagement
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2
    CodeBase: file:///C:/Users/willougd/AppData/Local/KeePass/PluginCache/DsCdPVEnlofsAPgS8vr9/CredentialManagement.DLL
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.32.0.23563
    Win32 Version: 2.32.0.23563
    CodeBase: file:///C:/Users/willougd/Downloads/KeePass-2.32/KeePass.XmlSerializers.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34291 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KoenZomers.OneDrive.Api
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Users/willougd/AppData/Local/KeePass/PluginCache/DsCdPVEnlofsAPgS8vr9/KoenZomers.OneDrive.Api.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34249 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by davehope** [comment]
I get this too, in my environment this is because the proxy uses NTLM to authenticate users.

Requests to live.github.com and api.onedrive.com result in a 407 response:

**Request Headers**

> CONNECT api.onedrive.com:443 HTTP/1.1
> Host: api.onedrive.com

**Response Headers:**
> HTTP/1.1 407 Unauthorized
> Content-Length: 6406
> Content-Type: text/html; charset=utf-8
> Proxy-Authenticate: Basic realm="FilteringProxy"
> X-Bst-Request-Id: *REMOVED*
> X-Bst-Info: *REMOVED*
> Pragma: No-cache
> Content-Language: en
> Cache-Control: No-cache
> Via: 1.1 *REMOVED*
> Connection: Keep-Alive
> Proxy-Connection: Keep-Alive

A similar request from a client that is capable of responding to the 407 response looks like the following:

**Request Headers (1/3)**

> CONNECT api.onedrive.com:443 HTTP/1.0
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
> Host: api.onedrive.com:443
> Content-Length: 0
> Proxy-Connection: Keep-Alive
> Pragma: no-cache

**Response Headers (1/3)**

> HTTP/1.1 407 Unauthorized
> Content-Length: 6406
> Content-Type: text/html; charset=utf-8
> **Proxy-Authenticate: NTLM**
> **Proxy-Authenticate: Basic realm="FilteringProxy"**
> X-Bst-Request-Id: *REMOVED*
> X-Bst-Info: *REMOVED*
> Pragma: No-cache
> Content-Language: en
> Cache-Control: No-cache
> Via: 1.1 *REMOVED*
> Connection: Keep-Alive
> Proxy-Connection: Keep-Alive
> Proxy-Support: Session-Based-Authentication

**Request Headers (2/3)**

> CONNECT api.onedrive.com:443 HTTP/1.0
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
> Host: api.onedrive.com:443
> Proxy-Connection: Keep-Alive
> Pragma: no-cache
> **Proxy-Authorization: NTLM TlR...*REMOVED***
> Content-Length: 0

**Response Headers (2/3)**

> HTTP/1.1 407 Unauthorized
> Content-Length: 15
> Content-Type: text/plain; charset=utf-8
> **Proxy-Authenticate: NTLM TlR*REMOVED***
> X-Bst-Request-Id: *REMOVED*
> Pragma: No-cache
> Cache-Control: No-cache
> Via: 1.1 *REMOVED*
> Connection: Keep-Alive
> Proxy-Connection: Keep-Alive
> Proxy-Support: Session-Based-Authentication
> 
> Type1 received.

**Request Headers (3/3)**

> CONNECT api.onedrive.com:443 HTTP/1.0
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
> Host: api.onedrive.com:443
> Proxy-Connection: Keep-Alive
> Pragma: no-cache
> Content-Length: 0
> **Proxy-Authorization: NTLM TlR*REMOVED***
> 

**Response Headers (3/3)**
> HTTP/1.1 200 OK
> .. etc

If there's anything further I can provide, please let me know. Wary of publishing an un-sanitized fiddler trace here.

**Comment by davehope** [comment]
Pre-Warning: its been a few years since I've done any C#.

Further to my previous message, using the following seems to solve the problem in a quick HttpClient test app I put together to reproduce this issue:

WebRequest.DefaultWebProxy.Credentials = CredentialCache.DefaultCredentials; 

A good reference for this is here:

https://blogs.msdn.microsoft.com/wsdevsol/2012/10/25/how-to-accommodate-authenticating-proxies-in-net/

Which works well for http traffic. However not so well for https as HttpClient.GetAsync() throws a HttpRequestException for https traffic.

**Comment by KoenZomers** [comment]
Thanks for all the input here. It's really hard for me to troubleshoot proxy issues as I don't have access to any kind of proxy myself, so I would have to shoot in the dark hoping to hit something. I did make an attempt to resolve this in version 1.5.1.0 I just released a minute ago. Can you guys try this version and see if it resolves the issue for you? Important to notice here is that under the KeePass proxy settings (KeePass > Tools > Options > Advanced tab > Proxy) you MUST set Authentication to Default credentials.

**Comment by KoenZomers** [comment]
Try it again with the latest version of the plugin I just released. I managed to build a Squid proxy myself with authentication so I could test the proxy scenarios. I fixed quite a few issues with proxies. Let me know if it resolved it for you please.

**Comment by KoenZomers** [comment]
Haven't heard back on this nor have I received any further complaints that it wouldn't work in the latest version. Therefore closing this issue.
