### ISSUE TITLE
Not deleting history

### ISSUE THREAD

**Issue by gabrielcsk** [KoenZomers/KeePassOneDriveSync#109]
My keepass is not deleting entry history. I've done the github procedures but keep downloading the histories, the trick I did was to limit the amount of histories and their size.
Do you know how I can solve this?

**Comment by KoenZomers** [comment]
Not sure what your exact scenario is. Do you mean you are using these KeePass settings:

![image](https://user-images.githubusercontent.com/5940670/62409551-85de9b80-b5d9-11e9-9e06-b810eaff5dde.png)

And if you change them, once KeePassOneDriveSync syncs your database, they get lost? I know the built into KeePass database merge functionality has some limitations around merging things which could involve this as well, which would be out of my control.

Can you first provide a bit more information on what you've done to see if we are on the same page?

**Comment by gabrielcsk** [comment]
My scenario is the same as the others. the history of entries returns when the plugin is synced.

**Comment by KoenZomers** [comment]
Then this is indeed caused by a current limitation in KeePass and is not something I can fix. Upvote the following suggestion to try to move the maker of KeePass to fix this: https://sourceforge.net/p/keepass/feature-requests/1463/

As a workaround as this suggestion is open for 8.5 years already thus doesn't have much chance for follow up, limit the history and manually upload your KeePass database over the existing one on SharePoint once.

**Comment by gabrielcsk** [comment]
Ok, thanks!
