### ISSUE TITLE
Error with Plugin v2.1.1.0 - De volgende plugin is niet compatible met de huidige versie van KeePass

### ISSUE THREAD

**Issue by rolandraijmakers** [KoenZomers/KeePassOneDriveSync#125]
Installed KeePass version 2.43   (D:\Applicaties\KeePass\KeePass.EXE)
Plugins directory (D:\Applicaties\KeePass\Plugins)    KeeOneDriveSync.plgx V2.1.1.0
PluginCache directory (D:\Applicaties\KeePass\PluginCache)
Shared directory for multiple users on an Microsoft RDS Server.

Error message: "De volgende plugin is niet comatible met de huidige versie van KeePass"
"D:\Applicaties\KeePass\PluginCache...\KoenZomersKeePassOneDriveSync.dll"

Kijk op de website van de plugin voor een geschikte versie.

De invoer is geen geldige Base-64-tekenreeks,
Rest zie plaatjes.

Verder de inhoud van de PluginCache directory screenshot met de versienummers van de DLL's 

![2020-01-03 11_35_18-KeePassOneDriveSync - Foutmelding (1) ](https://user-images.githubusercontent.com/46449678/71720104-c197be80-2e20-11ea-8e64-9de3d27076e0.png)

![2020-01-03 11_48_33-KeePassOneDriveSync - Foutmelding (2) PluginCache folder installed DLL's](https://user-images.githubusercontent.com/46449678/71720126-d96f4280-2e20-11ea-8301-f0655bbc2efa.png)

**Comment by KoenZomers** [comment]
Is this a new install of KeePass and this plugin on this machine or did you upgrade from an earlier version? It seems like it is unable to decrypt the configuration of the plugin. Since version 2.0.6.0 this has changed. If you're upgrading from a version before this one, ensure you delete your synced entries first and set them up again. If you didn't upgrade, it could be that some machine policy is preventing the plugin access to the decryption library of Windows and/or its keys. Are you on a machine with customized/strict security policies?

**Comment by rolandraijmakers** [comment]
Problem is solved. 
Our IT Provider deploys packages via SCCM. for KeePass and the plugins an installer package was made couple of months ago. They updated KeePassOneDriveSync from 2.0.5.0 to 2.1.1.0 manualy by copying the file KeeOneDriveSync.plgx 2.1.1.0 into the Plugins Directory. 
The Next day there was an automatic roll-back of the plugin to 2.0.5.0.

Now they have (i think upgraded the install package) to 2.1.1.0.
For myself I deleted the section voor KeePassOneDriveSync in the KeePass.config.XML; and setup the sync options again.

Thank you for your support.

Roland

**Comment by KoenZomers** [comment]
Good to see it being resolved. Thanks for reporting back!
