### ISSUE TITLE
[FEATURE REQUEST] Microsoft End of life of Azure AD (MsGraph)

### ISSUE THREAD

**Issue by rolandraijmakers** [KoenZomers/KeePassOneDriveSync#148]
Microsoft is updating Azure. 
In that context the've announced the end-of-life 30-6-20202 op Azure AD (MsGraph) and show alternative ways for authentication to OneDrive 
https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview

In which way is KeePassOneDriveSync affected?
Are there plans for updating KeePassOneDriveSync?

**Comment by KoenZomers** [comment]
Excellent question @rolandraijmakers. To jump directly to the answer: no, it will not impact this plugin.

The part that has been deprecated is the use of the Azure Active Directory Graph API (graph.windows.net). This was used to interact with users inside an Azure Active Directory. Since a few years we pretty much have similar functionality available through the Microsoft Graph API (graph.microsoft.com) which is where Microsoft will continue to invest in. This plugin does not have any interaction with Azure Active Directory and it already uses the Microsoft Graph API for all of its communication, if you have selected the recommended option. If not, still no issue as then the OneDrive APIs are used, which also have nothing to do with graph.windows.net.

**Comment by rolandraijmakers** [comment]
Thank you for the quick response. For an outsider it's difficult to see the difference between the two API's.

**Comment by KoenZomers** [comment]
Totally understand. No worries. Never hurts to ask. Better be safe than sorry!
