### ISSUE TITLE
Unused Icons Re-occur after Sync

### ISSUE THREAD

**Issue by EMLVIRUS** [KoenZomers/KeePassOneDriveSync#30]
Environ.
Keepass 2.x, KeePassOneDriveSync 1.x

STR:
1. create 2 new entries and import 2 different new image files as icons
2. establish sync and keep token inside database.
3. remove either one of the entry **_COMPLETELY_**.
4. in Keepass main windows, navigate to `Tools`→`Database Tools`, choose `Delete Unused Custom Icons`
5. re-sync

Actual result:
The locally removed icon re-occurred. The only solution is to remove remote database and re-upload.

**Comment by KoenZomers** [comment]
Thanks @EMLVIRUS for bringing this to my attention. I apologize for the long turnaround on this report. I managed to successfully reproduce the issue. I'm afraid however that the issue lies within the Sync functionality contained within the KeePass code. There's nothing specific I do in my plugin code to sync images\icons. For me it's one database all together and I'll let KeePass sync two databases. I only add the magic around uploading and downloading the databases from OneDrive (for Business).

I would recommend you to report this issue in the KeePass forum here: https://sourceforge.net/p/keepass/discussion/329221/ . Dominik is usually really good at replying to issues reported to KeePass there.

**Comment by EMLVIRUS** [comment]
@KoenZomers Just a shameless request: could u help me to post it here? I'm China now and have some troubles register a new account (GitHub has severe ping too) and feel free to close here.

**Comment by KoenZomers** [comment]
@EMLVIRUS, I've created a forum topic for this issue here:
https://sourceforge.net/p/keepass/discussion/329221/thread/89feb902/

**Comment by EMLVIRUS** [comment]
this issue exists since 2009 as a feature request. I guess they are unlike to fix that.

**Comment by KoenZomers** [comment]
I see. Shame. Well at least we know for sure now it's not in the plugin code. Unfortunately nothing else I can do from my end so I'll proceed with closing this issue.
