### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by KonFey** [KoenZomers/KeePassOneDriveSync#31]
Hi,
great plugin and real helpful- thanks.
The plugin works fine in a home environment. At work, network connectivity is different and I get an unhandled exception - Proxy authentication required.
Maybe you cannot work around the proxy thing, but at least the code should handle the error gracefully, I think:
![image](https://user-images.githubusercontent.com/31243074/29562817-32386d0e-873b-11e7-83c3-45a3d70e99ba.png)
Thanks, konfey

**Comment by KoenZomers** [comment]
You're right @KonFey, the error handling could be improved. Reason why I haven't done that yet is because these maybe ugly standard dialogs give perfect details on where the issue happened which helps me a lot in tracking down the cause. Replacing the dialog box with something more friendly is easy, but it would mean I have to build in a whole lot of custom logging stuff to make sure the same info stays available somewhere in case of troubleshooting. This same logging should also not contain any confidential stuff as it will be written plain to the disk. So I guess you can feel it coming why I haven't done so yet. It should only happen in exceptional cases anyway.

Did you get around the proxy issue though? I've had quite a few requests on proxy stuff in the past and tried to get it fixed back then (> 1 year ago). Haven't heard any more complaints since. Did you explicitly enable the proxy in KeePass? Check https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Troubleshooting.md

**Comment by KonFey** [comment]
Thanks Koen for quick reply. Problem was on my side and your suggested proxy help worked. I looked in the wrong area -  I did not expect KeePass to directly configure the networking stuff and couldn't find any settings in your plugin. Can you combine to not fully handle the exception (so that you get a full trace)  but still provide a tip to the troubleshooting doc when an exception occurs - that would have helped me to solve the issue by myself.
Regards, konfey
