### ISSUE TITLE
OneDrive for Business token error 

### ISSUE THREAD

**Issue by LudekK** [KoenZomers/KeePassOneDriveSync#51]
Hallo, OneDrive token error occured in the synchronization with OneDrive for Business. Screenshot is attached. This situation started 3 days ago, till that synchronization worked without problems. Complete reinstallation and usage portable version did not fixed this problem.
Best regards, Ludek
![bugkeepasssynchroonedrvfb](https://user-images.githubusercontent.com/36100331/35766064-cf927d4e-08d0-11e8-93be-44eaf2950bf8.JPG)

**Comment by KoenZomers** [comment]
Thanks! I'm guessing my app registration has expired. Are you using the graph option or direct OneDrive for business option?

**Comment by LudekK** [comment]
Hallo, I am using direct OneDrive for Business.

**Comment by KoenZomers** [comment]
Roger that. I'll validate the app registration and report back.

**Comment by KoenZomers** [comment]
It was indeed that the client secret expired on February 2, 2018. I've generated a new client secret and since AAD now allows for generating tokens that no longer expire ever, this issue should be fixed once and for all. Grab the [new version](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.1.2) and please met me know if it works again for you.

**Comment by LudekK** [comment]
New version works, so problem is fixed. Thanks.


LUDĚK KOLISKO
ICT manažer

Tel.: 773 623 044
ludek.kolisko@sos-vesnicky.cz<mailto:ludek.kolisko@sos-vesnicky.cz>

**Comment by KoenZomers** [comment]
Thanks for confirming!
