### ISSUE TITLE
Permission Request XML granting less-permissive access to oAuth token

### ISSUE THREAD

**Issue by awesomecogs** [KoenZomers/KeePassOneDriveSync#65]
Thanks for the **AWESOME** plugin, Koen!

Your steps [here](https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Configuration.md) worked great for creating the oAuth token.  One thing that bothered me was the full permission granted to that application for the entire SharePoint site.  I did a little testing and found the following XML works for giving write access to one particular list (which would contain the KDBX file)...

```XML
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web/list" Right="Write" />
</AppPermissionRequests>
```

The workflow for this process changes a little bit...
1. It is assumed a new SharePoint list has been created for the KDBX file before step 8
2. The trust dialog shown in step 12 will now have a drop-down saying "Let it edit or delete documents and list items in the list:" where the user must choose the list to grant write access to.  The name will match the new SharePoint list that was created

I think this is a much safer way to go and may allow less resistance from the site administrator as opposed to creating an oAuth token that grants full site access.

Thanks again for the plugin!

**Comment by KoenZomers** [comment]
Hi @awesomecogs. You're right, that one fits in with the least privileges principle. The steps to set this OAuth trust up are already quite tricky and error prone. I've often seen people go wrong on the selection list where you need to select the document library. As there is no way at all after granting the trust to see for which specific document library you have granted the trust, it makes troubleshooting things if it doesn't turn out to work extremely hard. That's why I have chosen to describe the site collection full control option. Again, I agree it comes at the price of giving out more permissions that it would actually need. Let me update the help text based on your thoughts on this and see if I get an increased load of questions and issues on this. If so, I will revert it, if not, I'll keep it.

**Comment by KoenZomers** [comment]
Help document has been updated
https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Configuration.md
