### ISSUE TITLE
Can't navigate in Shared With Me folders

### ISSUE THREAD

**Issue by DerStimmler** [KoenZomers/KeePassOneDriveSync#68]
I have the problem that I can't navigate in my "Shared With Me" folders. 

So when I try to open a database I click on "File" --> "Open" --> "Open from OneDrive...". After that I choose Microsoft Graph and authenticate to OneDrive. The Refresh Token gets stored in the Windows Credential Manager. 
So far so good. 
But now when I have to select the KeePass database to open I click on the "Shared With Me" tab and can see the root folder which is shared with me and contains multiple other folders. But after I navigate into it, these other folders won't show up. So it's like:
*Shared Folder* --> nothing
The problem also occurs when I open a databases over "File" --> "Open" --> "Open file..." and then try to sync it. So basically everytime I have to navigate through the "Shared With Me" folders inside the dialog of KeePassOneDriveSync.

I have another computer where this Problem doesn't occure. There I can get to the folders inside by navigating like this:
*Shared Folder* --> Shared --> *Shared Folder* --> *folders inside*  (That I have to choose the *Shared Folder* two times might be the same issue as in #55 but at least it works)

I have KeePass v2.40 and KeePassOneDrive Sync v2.02 installed.

Sometimes I also get the following error message when I start KeePass.
![error message](https://user-images.githubusercontent.com/43130816/48893229-27550100-ee40-11e8-8abf-fb4c37a08933.PNG)

In addition to that I have to authenticate OneDrive everytime I close and open KeePass again and open a  database used with OneDriveSync **on the PC that works** although I choosed the Windows Credential Manager.

**Comment by KoenZomers** [comment]
Please address one issue per issue report to keep it manageable. The last issue with the credentials being asked for each time I ran into myself for the first time tonight. Not sure why as it worked fine before. It has something to do with the Windows APIs incorrectly stating that writing to the Credential Manager was successful while in fact it wasn't. Not sure if this is something I can fix. Need to take a deeper dive into it. For now as a workaround, choose to store the credentials locally and it should work fine.

For the one above, that should be fixed in the latest version now.

For the first one I find it hard if not impossible to troubleshoot. If it works on one of your machines but not on the other running the same code, I would have to know all the different variables to guess what it could be. One angle at this would be to run Fiddler on the machine where it doesn't work and send me the capture via e-mail. It will contain the tokens which grant access to your OneDrive though, so perhaps test this against a temporary OneDrive you set up and do not post your capture here on GitHub.

**Comment by KoenZomers** [comment]
Closing as no further input has been received.
