### ISSUE TITLE
MS Login script error - secure.aadcdn.microsoftonline-p.com

### ISSUE THREAD

**Issue by HansJustus1** [KoenZomers/KeePassOneDriveSync#76]
Hello,

First of all, thank you ever so much for the plugin. Highly useful and very appreciated.

I've run into an issue lately, but I don't know whether it's on your or my end.
Just thought I'd mention it.

When I connect to a synced database on OneDrive I get an error message while the Microsoft Account Login dialogue is loading. 

I'll try and translate the error:
"The property 'reject' could not be called. Line 21, Sign 25523, Code 0."
URL: https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8395.17/content/cdnbundles/oldconvergedlogin_pcore.min_z2qsp8b10e2xrib0uwoksg2.js

This only happens when I have just started KeePass, closing and reopening the database works fine. The login still works fine, whether I allow to keep running the script or not. I can still use the database just fine.
It does not happen with the login dialogue in other apps, only KeePass.

The only thing changed, since the error occurs is the autostart. For some reason KeePass wouldn't start at bootup, but was still listed in the ctrl-alt-del menu für autostart. So I manually wrote it in the registry and removed the old entry from the list shown in ctrl-alt-del.

I have not tried deleting the registry entry, because a) I don't really think it's because of that and b), I am worried about breaking my KeePass autostart, which I would like to keep.

I am running KeePass 2.4 on a Windows 10 pro machine.

Thank you again for your very helpful plugin.

Kind regards,

Hans

**Comment by KoenZomers** [comment]
@HansJustus1 thanks for reporting this. I could reproduce this. The error that is shown is purely informational indeed and doesn't impair the functionality. As I have no influence over the JavaScript error that gets thrown nor on how the Internet Explorer control which is used to perform the login process works, I have changed the Internet Explorer component to simply surpress JavaScript errors. That solves this issue.

Fixed in version https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.2.4

Clsoing this issue. Feel free to reopen if the issue still occurs with this new version.

**Comment by HansJustus1** [comment]
Thank you ever so much, it is very appreciated that you take the time to maintain this plugin. Also thumbs up for the TLS 1.2!!!!
