### ISSUE TITLE
Bypassing _"authenticate to Onedrive" popup?

### ISSUE THREAD

**Issue by gpion** [KoenZomers/KeePassOneDriveSync#81]
Every time I open a database synchronised to my Onedrive Entreprise account I'm getting  this _"authenticate to Onedrive"_/ "select account" _popup: https://i.imgur.com/zqMOUpv.png

How  can i skip this? (I'm not even asked to enter any credential: I only have to select account, and there is only one)

**Comment by gpion** [comment]
Selecting "KeePass database" instead of "Windows Credential Manager" to Store OneDrive Refresh Token fixed the issue for me
It seem that KeePassOneDriveSync is unable to add any entry in Windows Credential Manager on my laptop.

**Comment by gpion** [comment]
Looks similar to  #69

**Comment by KoenZomers** [comment]
I'm aware of this issue. Haven't had time yet to dive into it. I can reproduce it on my devices, so that will help. Will update this ticket when I got a chance to look into it.

**Comment by gpion** [comment]
Thanks, I'll stay tuned then

**Comment by KoenZomers** [comment]
Finally had time to dig into this one. Turns out that Microsoft has made the Refresh Tokens longer. Probably to increase the safety of them or store more information in the JWT tokens. This means they have become too large for the Windows Credential Manager to store them. I have no way to increase the storage space of the Windows Credential Manager. Remember it's also a Windows feature that dates many decades back and was never designed to store lengthy Refresh Tokens anyway. Only option I had was to remove it as an option to store the token as it doesn't work anymore anyway.

Remove your config, sync it again and store it in the KeePass database or on your local disk to get rid of this issue.

**Comment by Sebazzz** [comment]
@KoenZomers Isn't it possible to put the token on the disk somewhere, **encrypted** and keep the key to that encryption stored in the credential store? Or simply: store in a config file and use DPAPI to protect the refresh token.

**Comment by KoenZomers** [comment]
@Sebazzz there's a PR waiting to implement it that way here: https://github.com/KoenZomers/KeePassOneDriveSync/pull/89

I want to ensure the current issues with the syncing are resolved before I will look into merging this one, not to make it more difficult to find the root cause of issues if they occur.
