### ISSUE TITLE
SharePoint Online Connection failes

### ISSUE THREAD

**Issue by tees54** [KoenZomers/KeePassOneDriveSync#99]
Hi,
i have created the App an the Client ID and Secret, but cant get i working.
![Anmerkung 2019-06-26 105335](https://user-images.githubusercontent.com/29545133/60166018-aa886c00-9800-11e9-9bd5-ab7b5f8fa107.jpg)

I tried all versions of the url, but no chance. What is the correct url, the root sharepoint adress or the teamsite, or the library, or the complete path to keepass file?
I hope you can help me please.

Kind regards

**Comment by KoenZomers** [comment]
Hi @tees54, please have a look at the updated article here: https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Configuration.md#sharepoint-2013-2016-2019-and-sharepoint-online-support

I have updated it with detailed steps how to get this going.

Let me know if you can get it to work using this information.

**Comment by tees54** [comment]
Hi @KoenZomers , nice work. I can get it work well on my eu dev tenant, but not in the company tenant, where i think the problem is the german cloud.

**Comment by KoenZomers** [comment]
Country specific tenants are always a challenge due to their sight differences towards the normal multi tenant farms. I unfortunately don't have access to one to test out where it goes wrong. If you happen to be able to create a new empty sitecollection on yours and email me the client id and client secret for just that document library in it, I would be happy to see if I can get it to work.
